### ISSUE TITLE
Precompilation err

### ISSUE THREAD

**Issue by shayandavoodii** [JuliaDynamics/CausalityTools.jl#364] opened 2024-03-27 18:31 UTC
I just installed the `CausalityTools` package and I faced the following precompilation error:
<details>
<summary>error</summary>

```julia
precompile
Precompiling project...
  ✗ LinearSolve
  ✗ LinearSolve → LinearSolveRecursiveArrayToolsExt
  ✗ NonlinearSolve
  ✗ OrdinaryDiffEq
  ✗ DynamicalSystemsBase
  ✗ CausalityTools
  0 dependencies successfully precompiled in 76 seconds. 224 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

CausalityTools [5520caf5-2dd7-5c5d-bfcb-a00e56ac49f7]

Failed to precompile CausalityTools [5520caf5-2dd7-5c5d-bfcb-a00e56ac49f7] to "C:\\Users\\Shayan\\.julia\\compiled\\v1.10\\CausalityTools\\jl_785B.tmp".        
ERROR: LoadError: InitError: could not load library "C:\Users\Shayan\.julia\artifacts\627190b3418f9b1cfbbf9b16afba530328670386\bin\mkl_core.2.dll"
The specified module could not be found.
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl .\libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl .\libdl.jl:116
  [3] macro expansion
    @ C:\Users\Shayan\.julia\packages\JLLWrappers\pG9bm\src\products\library_generators.jl:63 [inlined]
  [4] __init__()
    @ MKL_jll C:\Users\Shayan\.julia\packages\MKL_jll\GxRJ5\src\wrappers\x86_64-w64-mingw32.jl:10
  [5] run_module_init(mod::Module, i::Int64)
    @ Base .\loading.jl:1134
  [6] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1122
  [7] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base .\loading.jl:1067
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base .\loading.jl:1581
  [9] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1938
 [10] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1812
 [11] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [12] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [13] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1803
 [14] macro expansion
    @ .\loading.jl:1790 [inlined]
 [15] macro expansion
    @ .\lock.jl:267 [inlined]
 [16] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1753
 [17] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [18] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [19] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1746
 [20] top-level scope
    @ C:\Users\Shayan\.julia\packages\Preferences\enLcN\src\Preferences.jl:51
 [21] include
    @ .\Base.jl:495 [inlined]
 [22] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base .\loading.jl:2222
 [23] top-level scope
    @ stdin:3
during initialization of module MKL_jll
in expression starting at C:\Users\Shayan\.julia\packages\LinearSolve\z86Hi\src\LinearSolve.jl:1
in expression starting at stdin:3
ERROR: LoadError: Failed to precompile LinearSolve [7ed4a6bd-45f5-4d41-b270-4a48e9bafcae] to "C:\\Users\\Shayan\\.julia\\compiled\\v1.10\\LinearSolve\\jl_94E2.tmp".
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base .\loading.jl:2468
  [3] compilecache
    @ .\loading.jl:2340 [inlined]
  [4] (::Base.var"#968#969"{Base.PkgId})()
    @ Base .\loading.jl:1974
  [5] mkpidlock(f::Base.var"#968#969"{Base.PkgId}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64, wait::Bool})
    @ FileWatching.Pidfile C:\Users\Shayan\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\FileWatching\src\pidfile.jl:93
  [6] #mkpidlock#6
    @ C:\Users\Shayan\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\FileWatching\src\pidfile.jl:88 [inlined]
  [7] trymkpidlock(::Function, ::Vararg{Any}; kwargs::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile C:\Users\Shayan\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\FileWatching\src\pidfile.jl:111
  [8] #invokelatest#2
    @ .\essentials.jl:894 [inlined]
  [9] invokelatest
    @ .\essentials.jl:889 [inlined]
 [10] maybe_cachefile_lock(f::Base.var"#968#969"{Base.PkgId}, pkg::Base.PkgId, srcpath::String; stale_age::Int64)
    @ Base .\loading.jl:2983
 [11] maybe_cachefile_lock
    @ .\loading.jl:2980 [inlined]
 [12] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1970
 [13] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1812
 [14] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [15] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [16] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1803
 [17] macro expansion
    @ .\loading.jl:1790 [inlined]
 [18] macro expansion
    @ .\lock.jl:267 [inlined]
 [19] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1753
 [20] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [21] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [22] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1746
 [23] include
    @ .\Base.jl:495 [inlined]
 [24] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base .\loading.jl:2222
 [25] top-level scope
    @ stdin:3
in expression starting at C:\Users\Shayan\.julia\packages\OrdinaryDiffEq\ZbQoo\src\OrdinaryDiffEq.jl:1
in expression starting at stdin:3
ERROR: LoadError: Failed to precompile OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed] to "C:\\Users\\Shayan\\.julia\\compiled\\v1.10\\OrdinaryDiffEq\\jl_89D6.tmp".
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base .\loading.jl:2468
  [3] compilecache
    @ .\loading.jl:2340 [inlined]
  [4] (::Base.var"#968#969"{Base.PkgId})()
    @ Base .\loading.jl:1974
  [5] mkpidlock(f::Base.var"#968#969"{Base.PkgId}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64, wait::Bool})
    @ FileWatching.Pidfile C:\Users\Shayan\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\FileWatching\src\pidfile.jl:93
  [6] #mkpidlock#6
    @ C:\Users\Shayan\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\FileWatching\src\pidfile.jl:88 [inlined]
  [7] trymkpidlock(::Function, ::Vararg{Any}; kwargs::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile C:\Users\Shayan\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\FileWatching\src\pidfile.jl:111
  [8] #invokelatest#2
    @ .\essentials.jl:894 [inlined]
  [9] invokelatest
    @ .\essentials.jl:889 [inlined]
 [10] maybe_cachefile_lock(f::Base.var"#968#969"{Base.PkgId}, pkg::Base.PkgId, srcpath::String; stale_age::Int64)
    @ Base .\loading.jl:2983
 [11] maybe_cachefile_lock
    @ .\loading.jl:2980 [inlined]
 [12] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1970
 [13] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1812
 [14] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [15] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [16] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1803
 [17] macro expansion
    @ .\loading.jl:1790 [inlined]
 [18] macro expansion
    @ .\lock.jl:267 [inlined]
 [19] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1753
 [20] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [21] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [22] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1746
 [23] include(mod::Module, _path::String)
    @ Base .\Base.jl:495
 [24] include(x::String)
    @ DynamicalSystemsBase C:\Users\Shayan\.julia\packages\DynamicalSystemsBase\UaEOf\src\DynamicalSystemsBase.jl:1
 [25] top-level scope
    @ C:\Users\Shayan\.julia\packages\DynamicalSystemsBase\UaEOf\src\DynamicalSystemsBase.jl:24
 [26] include
    @ .\Base.jl:495 [inlined]
 [27] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base .\loading.jl:2222
 [28] top-level scope
    @ stdin:3
in expression starting at C:\Users\Shayan\.julia\packages\DynamicalSystemsBase\UaEOf\src\core_systems\continuous_time_ode.jl:1
in expression starting at C:\Users\Shayan\.julia\packages\DynamicalSystemsBase\UaEOf\src\DynamicalSystemsBase.jl:1
in expression starting at stdin:3
ERROR: LoadError: Failed to precompile DynamicalSystemsBase [6e36e845-645a-534a-86f2-f5d4aa5a06b4] to "C:\\Users\\Shayan\\.julia\\compiled\\v1.10\\DynamicalSystemsBase\\jl_7FB4.tmp".
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base .\loading.jl:2468
  [3] compilecache
    @ .\loading.jl:2340 [inlined]
  [4] (::Base.var"#968#969"{Base.PkgId})()
    @ Base .\loading.jl:1974
  [5] mkpidlock(f::Base.var"#968#969"{Base.PkgId}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64, wait::Bool})
    @ FileWatching.Pidfile C:\Users\Shayan\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\FileWatching\src\pidfile.jl:93
  [6] #mkpidlock#6
    @ C:\Users\Shayan\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\FileWatching\src\pidfile.jl:88 [inlined]
  [7] trymkpidlock(::Function, ::Vararg{Any}; kwargs::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile C:\Users\Shayan\.julia\juliaup\julia-1.10.2+0.x64.w64.mingw32\share\julia\stdlib\v1.10\FileWatching\src\pidfile.jl:111
  [8] #invokelatest#2
    @ .\essentials.jl:894 [inlined]
  [9] invokelatest
    @ .\essentials.jl:889 [inlined]
 [10] maybe_cachefile_lock(f::Base.var"#968#969"{Base.PkgId}, pkg::Base.PkgId, srcpath::String; stale_age::Int64)
    @ Base .\loading.jl:2983
 [11] maybe_cachefile_lock
    @ .\loading.jl:2980 [inlined]
 [12] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1970
 [13] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1812
 [14] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [15] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [16] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1803
 [17] macro expansion
    @ .\loading.jl:1790 [inlined]
 [18] macro expansion
    @ .\lock.jl:267 [inlined]
 [19] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1753
 [20] #invoke_in_world#3
    @ .\essentials.jl:926 [inlined]
 [21] invoke_in_world
    @ .\essentials.jl:923 [inlined]
 [22] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1746
 [23] include
    @ .\Base.jl:495 [inlined]
 [24] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base .\loading.jl:2222
 [25] top-level scope
    @ stdin:3
in expression starting at C:\Users\Shayan\.julia\packages\CausalityTools\alYDd\src\CausalityTools.jl:2
in expression starting at stdin:
```
</details>

is this known? I didn't find any similar issue so I opened this issue to report it.

**Comment by Datseris** [comment] 2024-04-16 20:50
Can you please do me a favor and confirm that you have run the package command in a _clean_ environment with no other packages installed?

(do `Pkg.activate("new_test_env")` to launch a new clean environment)

**Comment by shayandavoodii** [comment] 2024-04-18 15:11
> Can you please do me a favor and confirm that you have run the package command in a _clean_ environment with no other packages installed?
> 
> (do `Pkg.activate("new_test_env")` to launch a new clean environment)

Sure! 

```julia
pkg> activate --temp
  Activating new project at `C:\Users\Shayan\AppData\Local\Temp\jl_FeF090`

(jl_FeF090) pkg> add CausalityTools
   Resolving package versions...
   Installed SimpleNonlinearSolve ────── v1.7.0
   Installed NonlinearSolve ──────────── v3.10.0
   Installed LazyArrays ──────────────── v1.9.1
   Installed DiffEqBase ──────────────── v6.149.0
   Installed TriangularSolve ─────────── v0.2.0
   Installed MaybeInplace ────────────── v0.1.2
   Installed MatrixFactorizations ────── v2.2.0
   Installed ArrayLayouts ────────────── v1.9.2
   Installed SciMLBase ───────────────── v2.33.1
   Installed FiniteDiff ──────────────── v2.23.1
   Installed DynamicalSystemsBase ────── v3.8.1
   Installed EnzymeCore ──────────────── v0.6.6
   Installed VectorizationBase ───────── v0.21.66
   Installed LoopVectorization ───────── v0.12.169
   Installed SymbolicIndexingInterface ─ v0.3.16
   Installed RecursiveFactorization ──── v0.2.23
    Updating `C:\Users\Shayan\AppData\Local\Temp\jl_FeF090\Project.toml`
  [5520caf5] + CausalityTools v2.10.1
    Updating `C:\Users\Shayan\AppData\Local\Temp\jl_FeF090\Manifest.toml`
  [47edcb42] + ADTypes v0.2.7
  [621f4979] + AbstractFFTs v1.5.0
  [7d9f7c33] + Accessors v0.1.36
  [79e6a3ab] + Adapt v4.0.4
  [ec485272] + ArnoldiMethod v0.4.0
  [4fba245c] + ArrayInterface v7.9.0
  [4c555306] + ArrayLayouts v1.9.2
⌃ [13072b0f] + AxisAlgorithms v1.0.1
  [62783981] + BitTwiddlingConvenienceFunctions v0.1.5
  [2a0fbf3d] + CPUSummary v0.2.4
  [49dc2e85] + Calculus v0.5.1
  [5520caf5] + CausalityTools v2.10.1
  [d360d2e6] + ChainRulesCore v1.23.0
  [fb6a15b2] + CloseOpenIntervals v0.1.12
  [35d6a980] + ColorSchemes v3.24.0
  [3da002f7] + ColorTypes v0.11.5
  [c3611d14] + ColorVectorSpace v0.10.0
  [5ae59095] + Colors v0.12.10
  [861a8166] + Combinatorics v1.0.2
  [38540f10] + CommonSolve v0.2.4
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v4.14.0
⌅ [ab4b797d] + ComplexityMeasures v2.8.0
  [a33af91c] + CompositionsBase v0.1.2
  [2569d6c7] + ConcreteStructs v0.2.3
  [187b0558] + ConstructionBase v1.5.5
  [d38c429a] + Contour v0.6.3
  [adafc99b] + CpuId v0.3.1
  [a8cc5b0e] + Crayons v4.1.1
  [717857b8] + DSP v0.7.9
  [9a962f9c] + DataAPI v1.16.0
  [864edb3b] + DataStructures v0.18.20
  [e2d170a0] + DataValueInterfaces v1.0.0
  [5732040d] + DelayEmbeddings v2.7.4
  [8bb1440f] + DelimitedFiles v1.9.1
  [2b5f629d] + DiffEqBase v6.149.0
  [163ba53b] + DiffResults v1.1.0
  [b552c78f] + DiffRules v1.15.1
  [b4f34e82] + Distances v0.10.11
  [31c24e10] + Distributions v0.25.107
  [ffbed154] + DocStringExtensions v0.9.3
  [fa6b7ba4] + DualNumbers v0.6.8
  [6e36e845] + DynamicalSystemsBase v3.8.1
  [4e289a0a] + EnumX v1.0.4
⌃ [f151be2c] + EnzymeCore v0.6.6
  [d4d017d3] + ExponentialUtilities v1.26.1
  [e2ba6199] + ExprTools v0.1.10
  [7a1cc6ca] + FFTW v1.8.0
  [7034ab61] + FastBroadcast v0.2.8
  [9aa1b823] + FastClosures v0.3.2
  [29a986be] + FastLapackInterface v2.0.2
  [1a297f60] + FillArrays v1.10.0
  [6a86dc24] + FiniteDiff v2.23.1
  [53c48c17] + FixedPointNumbers v0.8.4
  [f6369f11] + ForwardDiff v0.10.36
  [069b7b12] + FunctionWrappers v1.1.3
  [77dc65aa] + FunctionWrappersWrappers v0.1.3
  [46192b85] + GPUArraysCore v0.1.6
  [c145ed77] + GenericSchur v0.5.4
  [86223c79] + Graphs v1.10.0
  [3e5b6fbb] + HostCPUFeatures v0.1.16
  [34004b35] + HypergeometricFunctions v0.3.23
  [09f84164] + HypothesisTests v0.11.0
  [615f187c] + IfElse v0.1.1
  [d25df0c9] + Inflate v0.1.4
⌅ [a98d9a8b] + Interpolations v0.14.0
  [3587e190] + InverseFunctions v0.1.13
  [92d709cd] + IrrationalConstants v0.2.2
  [c8e1da08] + IterTools v1.10.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [692b3bcd] + JLLWrappers v1.5.0
  [ef3ab10e] + KLU v0.6.0
  [ba0b0d4f] + Krylov v0.9.5
  [2ee39098] + LabelledArrays v1.15.1
  [10f19ff3] + LayoutPointers v0.1.15
  [5078a376] + LazyArrays v1.9.1
  [d3d80556] + LineSearches v7.2.0
  [7ed4a6bd] + LinearSolve v2.28.0
  [2ab3a3ac] + LogExpFunctions v0.3.27
  [fc60dff9] + LombScargle v1.0.3
  [bdcacae8] + LoopVectorization v0.12.169
  [1914dd2f] + MacroTools v0.5.13
  [d125e4d3] + ManualMemory v0.1.8
  [299715c1] + MarchingCubes v0.1.9
  [a3b82374] + MatrixFactorizations v2.2.0
  [bb5d69b7] + MaybeInplace v0.1.2
  [eff96d63] + Measurements v2.11.0
  [e1d29d7a] + Missings v1.2.0
  [46d2c3a1] + MuladdMacro v0.2.4
  [d41bc354] + NLSolversBase v7.8.3
  [77ba4419] + NaNMath v1.0.2
  [b8a86587] + NearestNeighbors v0.4.16
  [645ca80c] + Neighborhood v0.2.4
  [8913a72c] + NonlinearSolve v3.10.0
  [6fe1bfb0] + OffsetArrays v1.14.0
  [bac558e1] + OrderedCollections v1.6.3
  [1dea7af3] + OrdinaryDiffEq v6.74.1
  [90014a1f] + PDMats v0.11.31
  [65ce6f38] + PackageExtensionCompat v1.0.2
  [d96e819e] + Parameters v0.12.3
  [f517fe37] + Polyester v0.7.13
  [1d0040c9] + PolyesterWeave v0.2.1
  [f27b6e38] + Polynomials v4.0.7
  [d236fae5] + PreallocationTools v0.4.21
  [aea7be01] + PrecompileTools v1.2.1
  [21216c6a] + Preferences v1.4.3
  [92933f4c] + ProgressMeter v1.10.0
  [1fd47b50] + QuadGK v2.9.4
  [c84ed2f1] + Ratios v0.4.5
  [3cdcf5f2] + RecipesBase v1.3.4
  [639c3291] + RecurrenceAnalysis v2.0.6
  [731186ca] + RecursiveArrayTools v3.13.0
  [f2c3362d] + RecursiveFactorization v0.2.23
  [189a3867] + Reexport v1.2.2
  [ae029012] + Requires v1.3.0
  [79098fc4] + Rmath v0.7.1
  [f2b01f46] + Roots v2.1.5
  [7e49a35a] + RuntimeGeneratedFunctions v0.5.13
  [94e857df] + SIMDTypes v0.1.0
  [476501e8] + SLEEFPirates v0.6.42
  [0bca4576] + SciMLBase v2.33.1
  [c0aeaf25] + SciMLOperators v0.3.8
  [53ae85a6] + SciMLStructures v1.1.0
  [6c6a2e73] + Scratch v1.2.1
  [efcf1570] + Setfield v1.1.1
  [05bca326] + SimpleDiffEq v1.11.1
  [727e6d20] + SimpleNonlinearSolve v1.7.0
  [699a6c99] + SimpleTraits v0.9.4
  [ce78b400] + SimpleUnPack v1.1.0
  [a2af1166] + SortingAlgorithms v1.2.1
  [47a9eef4] + SparseDiffTools v2.17.0
  [e56a9233] + Sparspak v0.3.9
  [276daf66] + SpecialFunctions v2.3.1
  [40b095a5] + StateSpaceSets v1.4.5
  [aedffcd0] + Static v0.8.10
  [0d7ed370] + StaticArrayInterface v1.5.0
  [90137ffa] + StaticArrays v1.9.3
  [1e83bf80] + StaticArraysCore v1.4.2
  [82ae8749] + StatsAPI v1.7.0
  [2913bbd2] + StatsBase v0.34.3
  [4c63d2b9] + StatsFuns v1.3.1
  [7792a7ef] + StrideArraysCore v0.5.5
  [2efcf032] + SymbolicIndexingInterface v0.3.16
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.11.1
  [62fd8b95] + TensorCore v0.1.1
  [8290d209] + ThreadingUtilities v0.5.2
  [a759f4b9] + TimerOutputs v0.5.23
  [c804724b] + TimeseriesSurrogates v2.6.4
  [d5829a12] + TriangularSolve v0.2.0
  [410a4b4d] + Tricks v0.1.8
  [781d530d] + TruncatedStacktraces v1.4.0
  [3a884ed6] + UnPack v1.0.2
  [b8865327] + UnicodePlots v3.6.4
  [3d5dd08c] + VectorizationBase v0.21.66
  [19fa3120] + VertexSafeGraphs v0.2.0
⌅ [29a6e085] + Wavelets v0.9.5
⌅ [efce3f68] + WoodburyMatrices v0.5.6
  [f5851436] + FFTW_jll v3.3.10+0
  [1d5cc7b8] + IntelOpenMP_jll v2024.0.2+0
  [856f044c] + MKL_jll v2024.0.0+0
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [f50d1b31] + Rmath_jll v0.4.0+0
  [0dad84c5] + ArgTools v1.1.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [9fa8497b] + Future
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL v0.6.4
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.10.0
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays v1.10.0
  [10745b16] + Statistics v1.10.0
  [4607b0f0] + SuiteSparse
  [fa267f1f] + TOML v1.0.3
  [a4e569a6] + Tar v1.10.0
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll v1.1.0+0
  [deac9b47] + LibCURL_jll v8.4.0+0
  [e37daf67] + LibGit2_jll v1.6.4+0
  [29816b5a] + LibSSH2_jll v1.11.0+1
  [c8ffd9c3] + MbedTLS_jll v2.28.2+1
  [14a3606d] + MozillaCACerts_jll v2023.1.10
  [4536629a] + OpenBLAS_jll v0.3.23+4
  [05823500] + OpenLibm_jll v0.8.1+2
  [bea87d4a] + SuiteSparse_jll v7.2.1+1
  [83775a58] + Zlib_jll v1.2.13+1
  [8e850b90] + libblastrampoline_jll v5.8.0+1
  [8e850ede] + nghttp2_jll v1.52.0+1
  [3f19e933] + p7zip_jll v17.4.0+2
        Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`
Precompiling project...
  ✓ StatsBase
  ✗ LinearSolve
  ✗ LinearSolve → LinearSolveRecursiveArrayToolsExt
  ✗ NonlinearSolve
  ✗ OrdinaryDiffEq
  ✗ DynamicalSystemsBase
  ✗ CausalityTools
  66 dependencies successfully precompiled in 238 seconds. 155 already precompiled.
  1 dependency precompiled but a different version is currently loaded. Restart julia to access the new version
  1 dependency had output during precompilation:
┌ Interpolations
│  WARNING: method definition for checkbounds at C:\Users\Shayan\.julia\packages\Interpolations\USkTk\src\Interpolations.jl:454 declares type variable N but does not use it.
│  WARNING: method definition for checkbounds at C:\Users\Shayan\.julia\packages\Interpolations\USkTk\src\Interpolations.jl:457 declares type variable N but does not use it.
│  WARNING: method definition for GriddedInterpolation at C:\Users\Shayan\.julia\packages\Interpolations\USkTk\src\gridded\gridded.jl:37 declares type variable pad but does not use it.
│  WARNING: method definition for GriddedInterpolation at C:\Users\Shayan\.julia\packages\Interpolations\USkTk\src\gridded\gridded.jl:60 declares type variable pad but does not use it.
│  WARNING: method definition for interpolate! at C:\Users\Shayan\.julia\packages\Interpolations\USkTk\src\deprecations.jl:30 declares type variable TWeights but does not use it.
└
  6 dependencies errored.
  For a report of the errors see `julia> err`. To retry use `pkg> precompile`

(jl_FeF090) pkg> st
Status `C:\Users\Shayan\AppData\Local\Temp\jl_FeF090\Project.toml`
  [5520caf5] CausalityTools v2.10.1
```

**Comment by Datseris** [comment] 2024-04-18 15:16
LinearSolve.jl does not compile. It doesn't find an MKL library from what I can tell. cc @ChrisRackauckas perhaps you can link user @shayandavoodii on how to solve this? Maybe you have gotten such an error report before.

**Comment by ChrisRackauckas** [comment] 2024-04-18 15:21
Actually looks like Windows, if you check that link do you find a binary there?

**Comment by shayandavoodii** [comment] 2024-04-18 15:22
> Actually looks like Windows
Yes. I installed the latest Julia release using Juliaup.

**Comment by ChrisRackauckas** [comment] 2024-04-18 15:35
Confirm the MKL binary existance?

**Comment by Datseris** [comment] 2024-05-01 10:10
I am closing this, please re-open if reproducible example is given. In any case this is very likely unrelated with CausalityTools.jl itself.

**Closed by Datseris** 2024-05-01 10:10 UTC
