### ISSUE TITLE
Replicating Schreiber: nonzero TE at zero interaction and no directionality 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/CausalityTools.jl#122] opened 2020-01-28 14:05 UTC
Hey there,

A good example to have in the docs is replicating the original work that introduces the concept. I often do this in DynamicalSystems.jl and I wanted to contribute this here as well. This is the code snippet I have created, which will of course be modified once #120 is closed.

```julia
using DynamicalSystems, CausalityTools, PyPlot, Random
Random.seed!(1234)

function ulam(dx, x, p, t)
    f(x) = 2 - x^2
    ε = p[1]
    dx[1] = f(ε*x[length(dx)] + (1-ε)*x[1])
    for i in 2:length(dx)
        dx[i] = f(ε*x[i-1] + (1-ε)*x[i])
    end
end

ds = DiscreteDynamicalSystem(ulam, rand(100) .- 0.5, [0.04])
tr = trajectory(ds, 1000; Ttr = 1000)

εs = 0.0:0.01:1.0
te = zero(εs); te2 = zero(εs)
for (i, ε) in enumerate(εs)
    set_parameter!(ds, 1, ε)
    tr = trajectory(ds, 10000; Ttr = 10000)
    X1 = tr[:, 1]; X2 = tr[:, 2]
    @assert !any(isnan, X1)
    @assert !any(isnan, X2)
    t = transferentropy(X1, X2, RectangularBinning(0.01), 1, 1, 1)
    te[i] = t
    te2[i] = transferentropy(X2, X1, RectangularBinning(0.01), 1, 1, 1)
end

plot(εs, te)
plot(εs, te2, ls = "dashed")
```
running this code gives:

![Figure_1](https://user-images.githubusercontent.com/19669089/73270848-cf522100-41df-11ea-9e59-6c5801699f0a.png)

THe code tries to replicate the solid lines of Fig 2 from the 2000 PRL paper:

![image](https://user-images.githubusercontent.com/19669089/73270996-1b9d6100-41e0-11ea-8ad6-70e87e48f27b.png)

The upper curve is replicated, and I expect that the differences are due to me choosing a different estimation method and "discretization" than he does in this paper (he uses nearest neighbors and correlation sums), see the equation on $\hat{p}$ on the first page). 

But I have difficulty seeing why the following two things happen:

1. The transfer entropy does not go to zero for ε=0
2. The transfer entropy of X2 -> X1 is not only nonzero but almost identical to X1 -> X2, even though there is a transfer only in the latter.

---

When we clarify this I'll put this in the docs via a PR.

**Comment by kahaaga** [comment] 2020-01-28 14:53
Ah, excellent! This example should definitely be included in the docs once the new notation is in place. 

## Nonzero TE when there is no coupling

When computed numerically, non-coupled systems have nonzero TE in both directions, except if computed analytically. The easiest explanation for this is that we're using transfer entropy _estimators_ (as you mention) on finite data. In the limit of infinite data, a perfect transfer entropy estimator should give zero for non-coupled time series variables. There will always be some bias for the estimators, which some authors have attempted to quantify. I think there is a discussion on this in [Bossomaier et al.'s book](https://www.springer.com/gp/book/9783319432212). For nearest neighbors estimators, TE might even be negative (which is of course nonsensical, so corrections should be made). 

For autoregressive systems, one can actually compute transfer entropy exactly from the covariance matrix of the system (see [Hahs and Pethel (2013)](https://www.mdpi.com/1099-4300/15/3/767)). In this case, TE is actually precisely zero for zero coupling. I'm using their approach in our predictive asymmetry paper, so I can also prepare an example in the docs demonstrating this for transfer entropy.

## Your example

In general, one often finds that the _relative_ transfer entropy respects the underlying coupling strength, but that the absolute transfer entropy does not automatically drop to zero for zero coupling.


The discrepancy you see may indeed be because you're using a different estimator. When estimating TE from the density of partitioned state spaces, as you do here, values of the TE also depend on the size of the partition elements. Here, you use pretty small bins. I have found that going to "fine" with the binning with limited data sets often messes up the detection power for the method. Generally, I partition the state space into `N = n_pts^(1/(D+1))` intervals along each axis, where `n_pts` is the number of points in the time series and `D` is the total embedding dimension (including all marginals)

But let me investigate your example further and get back to you. There may be something else at play here.

**Comment by Datseris** [comment] 2020-01-28 15:29
Okay, thanks, I'll wait. Schreiber uses kernel sum as the method to estimate the joint probability, see his eq. about $\hat{p}$ in the first page. Is this method also implemented in CausalityTools.jl? At the moment I have only found `RectangularBinning` as a way to do this estimation. Seems that this "kernel sum" he uses in the paper is super trivial to implement numerically :D

**Comment by Datseris** [comment] 2020-01-28 16:40
You were right, seems like the binning was too naive. Successively increasing the bin width to 0.1 and then to 0.25 gives a totally different picture:

![Figure_1](https://user-images.githubusercontent.com/19669089/73284672-33cbab00-41f5-11ea-92c3-c9d85030f9c3.png)

**Comment by kahaaga** [comment] 2020-01-28 17:05
> You were right, seems like the binning was too naive. Successively increasing the bin width to 0.1 and then to 0.25 gives a totally different picture:

Ah, beautiful! That makes much more sense. 

For partition-based estimators, scaling the number of bins according to the number of observations available should always be done (i. e. avoid too many empty bins). 

Other estimators such as the nearest neighbor approach doesn't suffer from the same bias, but in turn has other parameters that need to be tuned. In fact, you may be *negative* transfer entropy for the nearest neighbor estimator. The advantage of the partition based estimator you used is that you are guaranteed `TE >= 0`.

So much for the non-parametric-ness of the method, huh? 🍺

**Comment by kahaaga** [comment] 2020-01-28 17:26
> Okay, thanks, I'll wait. Schreiber uses kernel sum as the method to estimate the joint probability, see his eq. about $\hat{p}$ in the second page. Is this method also implemented in CausalityTools.jl? At the moment I have only found RectangularBinning as a way to do this estimation. Seems that this "kernel sum" he uses in the paper is super trivial to implement numerically :D

The kernel approach is on the list of desired estimators. I do have an implementation of the kernel approach lying around somewhere, but I haven't tested it properly yet and merged it. Let me dig it up and check the state of it by trying to reproduce the same example as above! If it's not in a good state, it's up for grabs!

**Comment by Datseris** [comment] 2020-05-04 11:59
Did you find the implementation of the kernel method you were talking about? I've already applied TE to data I have, but I really need to have a second approach as well. My results were a bit inconclusive, and I want to test more numerically different methods before I turn to thinking whether this incoclusiveness is a true characteristic of my data.

**Closed** 2021-11-25 18:50 UTC
